-- Generated by Oracle SQL Developer Data Modeler 21.2.0.183.1957
--   at:        2022-01-08 15:01:13 EET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE achizitii (
    furnizori_id_furnizor NUMBER(5) NOT NULL,
    materiale_id_material NUMBER(5) NOT NULL,
    data                  DATE NOT NULL,
    cantitate             NUMBER(5) NOT NULL
);

ALTER TABLE achizitii
    ADD CONSTRAINT achizitii_pk PRIMARY KEY ( furnizori_id_furnizor,
                                              materiale_id_material,
                                              data );

CREATE TABLE angajati (
    id_angajat   NUMBER(5) NOT NULL,
    nume_angajat VARCHAR2(30) NOT NULL
);

ALTER TABLE angajati
    ADD CONSTRAINT nume_ck CHECK ( REGEXP_LIKE ( nume_angajat,
                                                 '^[a-zA-Z ]*$' ) );

ALTER TABLE angajati ADD CONSTRAINT angajati_pk PRIMARY KEY ( id_angajat );

CREATE TABLE cereri (
    angajati_id_angajat   NUMBER(5) NOT NULL,
    materiale_id_material NUMBER(5) NOT NULL,
    nr_cerere             NUMBER(5) NOT NULL,
    data_cerere           DATE NOT NULL,
    cantitate             NUMBER(3) NOT NULL,
    rezolvata             CHAR(2) NOT NULL
);

ALTER TABLE cereri
    ADD CONSTRAINT cerere_rezolvata CHECK ( rezolvata IN ( 'da', 'nu' ) );

ALTER TABLE cereri ADD CONSTRAINT cereri_pk PRIMARY KEY ( materiale_id_material,
                                                          nr_cerere );

CREATE TABLE detalii_angajati (
    id_angajat  NUMBER(5) NOT NULL,
    cnp         NUMBER(13) NOT NULL,
    departament VARCHAR2(20) NOT NULL,
    adresa      VARCHAR2(25),
    telefon     NUMBER(10) NOT NULL
);

ALTER TABLE detalii_angajati
    ADD CONSTRAINT cnp_ck CHECK ( length(cnp) = 13 );

ALTER TABLE detalii_angajati
    ADD CONSTRAINT telefon_ck CHECK ( REGEXP_LIKE ( telefon,
                                                    '^[0-9 ]*$' ) );

ALTER TABLE detalii_angajati ADD CONSTRAINT detalii_angajati_pk PRIMARY KEY ( id_angajat );

ALTER TABLE detalii_angajati ADD CONSTRAINT cnp_uk UNIQUE ( cnp );

CREATE TABLE furnizori (
    id_furnizor       NUMBER(5) NOT NULL,
    denumire_furnizor VARCHAR2(30) NOT NULL,
    sediu             VARCHAR2(15)
);

ALTER TABLE furnizori ADD CONSTRAINT furnizori_pk PRIMARY KEY ( id_furnizor );

CREATE TABLE materiale (
    id_material NUMBER(5) NOT NULL,
    denumire    VARCHAR2(30) NOT NULL,
    um          VARCHAR2(5) NOT NULL,
    stoc        NUMBER(7) NOT NULL,
    id_tip      NUMBER(5) NOT NULL
);

ALTER TABLE materiale
    ADD CONSTRAINT um_ck CHECK ( um IN ( 'buc', 'cutie', 'l', 'top' ) );

ALTER TABLE materiale ADD CONSTRAINT stock_ck CHECK ( stoc >= 0 );

ALTER TABLE materiale ADD CONSTRAINT materiale_pk PRIMARY KEY ( id_material );

CREATE TABLE tipuri_materiale (
    id_tip       NUMBER(5) NOT NULL,
    denumire_tip VARCHAR2(25) NOT NULL
);

ALTER TABLE tipuri_materiale ADD CONSTRAINT tipuri_materiale_pk PRIMARY KEY ( id_tip );

ALTER TABLE achizitii
    ADD CONSTRAINT achizitii_furnizori_fk FOREIGN KEY ( furnizori_id_furnizor )
        REFERENCES furnizori ( id_furnizor );

ALTER TABLE achizitii
    ADD CONSTRAINT achizitii_materiale_fk FOREIGN KEY ( materiale_id_material )
        REFERENCES materiale ( id_material );

ALTER TABLE cereri
    ADD CONSTRAINT cereri_angajati_fk FOREIGN KEY ( angajati_id_angajat )
        REFERENCES angajati ( id_angajat );

ALTER TABLE cereri
    ADD CONSTRAINT cereri_materiale_fk FOREIGN KEY ( materiale_id_material )
        REFERENCES materiale ( id_material );

ALTER TABLE detalii_angajati
    ADD CONSTRAINT detalii_angajati_fk FOREIGN KEY ( id_angajat )
        REFERENCES angajati ( id_angajat );

ALTER TABLE materiale
    ADD CONSTRAINT tipuri_materiale_fk FOREIGN KEY ( id_tip )
        REFERENCES tipuri_materiale ( id_tip );

CREATE SEQUENCE seq_angajati_id_angajat START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER trg_angajati_id_angajat BEFORE
    INSERT ON angajati
    FOR EACH ROW
    WHEN ( new.id_angajat IS NULL )
BEGIN
    :new.id_angajat := seq_angajati_id_angajat.nextval;
END;
/

CREATE SEQUENCE seq_cereri_nr_cerere START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER trg_cereri_nr_cerere BEFORE
    INSERT ON cereri
    FOR EACH ROW
    WHEN ( new.nr_cerere IS NULL )
BEGIN
    :new.nr_cerere := seq_cereri_nr_cerere.nextval;
END;
/

CREATE SEQUENCE seq_tipuri_materiale_id_tip START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER trg_tipuri_materiale_id_tip BEFORE
    INSERT ON tipuri_materiale
    FOR EACH ROW
    WHEN ( new.id_tip IS NULL )
BEGIN
    :new.id_tip := seq_tipuri_materiale_id_tip.nextval;
END;
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             7
-- CREATE INDEX                             0
-- ALTER TABLE                             20
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           3
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          3
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
